# Generated by Django 5.2.6 on 2025-10-05 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dificuldade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Dificuldades',
            },
        ),
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Linguagens',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('linguagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.linguagem')),
            ],
            options={
                'verbose_name_plural': 'Assuntos',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('explicacao', models.TextField(blank=True, help_text='Explicação exibida após o usuário responder.')),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.assunto')),
            ],
            options={
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='PerguntaDificuldade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.dificuldade')),
                ('pergunta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dificuldade_link', to='setup.pergunta')),
            ],
            options={
                'verbose_name_plural': 'Dificuldades das Perguntas',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('correta', models.BooleanField(default=False)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='setup.pergunta')),
            ],
            options={
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_perguntas', models.IntegerField()),
                ('acertos', models.IntegerField()),
                ('status', models.CharField(default='COMPLETO', max_length=12)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('assunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.assunto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.usuario')),
            ],
        ),
    ]
