# Generated by Django 5.2.6 on 2025-09-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='assunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.assunto'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='status',
            field=models.CharField(default='COMPLETO', max_length=12),
        ),
    ]
