# Generated by Django 5.2.6 on 2025-09-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_popular_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='explicacao',
            field=models.TextField(blank=True, help_text='Explicação exibida após o usuário responder.'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='setup.pergunta'),
        ),
    ]
