name: Build and deploy Python app to Azure Web App - code-quiz

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        
      - name: Run migrations to update db.sqlite3
        run: |
          python manage.py migrate

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x "venv/*" -x ".git/*" -x ".vscode/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build 
    
    steps:
      - name: 1. Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: 2. Fazer login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 3. Parar o Azure Web App
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp stop --name 'code-quiz' --resource-group 'code-quiz_group'

      - name: 4. Aguardar 30 segundos para estabilização
        run: sleep 30

      - name: 5. Fazer o deploy do pacote (release.zip)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'code-quiz'
          package: 'release.zip'

      - name: 6. Iniciar o Azure Web App
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp start --name 'code-quiz' --resource-group 'code-quiz_group'
            