name: Deploy App Django na Azure

on:
  push:
    branches: [ "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Baixar o código
      uses: actions/checkout@v3

    - name: 2. Configurar o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 3. Instalar as dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 4. Rodar os testes (se houver)
      run: |
        python manage.py test

  deploy:
    needs: build 
    runs-on: ubuntu-latest

    steps:
    - name: 1. Baixar o código
      uses: actions/checkout@v3

    - name: 2. Fazer login no Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 3. Fazer o deploy dos arquivos para o Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'code-quiz'
        package: '.'

    - name: 4. Executar as migrações no Azure
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az webapp run --name 'code-quiz' --resource-group 'code-quiz_group' --command "python manage.py flush --no-input && python manage.py migrate"