name: Build and deploy Python app to Azure Web App - code-quiz

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        
      - name: Run migrations to update db.sqlite3
        run: |
          python manage.py migrate

      - name: Zip artifact for deployment
        
        run: zip release.zip ./* -r -x "venv/*" -x ".git/*" -x ".vscode/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4 
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: 1. Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: 2. Fazer login no Azure
        uses: azure/login@v2 
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 3. Fazer o deploy do pacote (release.zip)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'code-quiz'
          package: 'release.zip'