name: Build and deploy Python app to Azure Web App - code-quiz

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run migrations for tests
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -v --tb=short
        env:
          DJANGO_SETTINGS_MODULE: project.settings

      - name: Load fixture data
        run: |
          source venv/bin/activate
          python manage.py loaddata setup/fixtures/quiz_data.json

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x "venv/*" -x ".git/*" -x ".vscode/*" -x "htmlcov/*" -x ".coverage"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'code-quiz'
          slot-name: 'Production'
          package: release.zip

      - name: Wait for deployment to stabilize
        run: sleep 45

      - name: Set startup command
        run: |
          az webapp config set --name code-quiz --resource-group code-quiz_group --startup-file "bash startup.sh"

      - name: Restart webapp to apply changes
        run: |
          az webapp restart --name code-quiz --resource-group code-quiz_group

      - name: Wait for webapp to be ready
        run: sleep 30

      - name: Check deployment logs
        run: |
          echo "Checking deployment logs..."
          timeout 30s az webapp log tail --name code-quiz --resource-group code-quiz_group || true
        continue-on-error: true

      - name: Logout from Azure
        run: az logout